name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region (e.g., us-west-1, us-east-1, etc.)

      # Step 4: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Step 5: Build Docker image and tag it as 'latest'
      - name: Build Docker image and tag as 'latest'
        run: |
          docker build \
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -t ${{ secrets.AWS_ECR_REPO }}:latest .

      # Step 6: Push Docker image to Amazon ECR
      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ECR_REPO }}:latest

      # Step 7: Update task definition
      - name: Update ECS task definition
        id: task-def-update
        run: |
          # Describe the current task definition
          aws ecs describe-task-definition --task-definition api --query taskDefinition > task-definition.json
    
          # Modify the task definition by updating the Docker image tag
          jq '.containerDefinitions[0].image = "${{ secrets.AWS_ECR_REPO }}:latest"' task-definition.json > new-task-definition.json

          # Register the new task definition
          NEW_TASK_DEF=$(aws ecs register-task-definition \
            --cli-input-json file://new-task-definition.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)
          
          echo "::set-output name=task-definition-arn::$NEW_TASK_DEF"

      # Step 8: Update ECS service with new task definition
      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster "api" \
            --service "api" \
            --task-definition ${{ steps.task-def-update.outputs.task-definition-arn }} \
            --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1  # Adjust as necessary
